---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-rds-external-secret
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${cluster_secret_store}
    kind: ClusterSecretStore
  target:
    name: harbor-rds-secret
    creationPolicy: Owner
  data:
    # REF: https://github.com/goharbor/harbor-helm/blob/v1.16.2/values.yaml#L941
  - secretKey: password
    remoteRef:
      key: ${harbor_rds_secret}
      property: password
