---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-s3-external-secret
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${cluster_secret_store}
    kind: ClusterSecretStore
  target:
    name: harbor-s3-secret
    creationPolicy: Owner
  data:
    # REF: https://github.com/goharbor/harbor-helm/blob/v1.16.2/values.yaml#L215-L216
  - secretKey: REGISTRY_STORAGE_S3_ACCESSKEY
    remoteRef:
      key: ${harbor_iam_secret}
      property: AWS_ACCESS_KEY_ID
  - secretKey: REGISTRY_STORAGE_S3_SECRETKEY
    remoteRef:
      key: ${harbor_iam_secret}
      property: AWS_SECRET_ACCESS_KEY
